### ISSUE TITLE
Uncaught ReferenceError: XsltForms_domEngine is not defined

### ISSUE THREAD

**Issue by nkbl** [AlainCouthures/xsltforms#16]
Is there anything I need, besides build files, for this library to work? (I'm trying to update from r612 to the latest).

**Comment by AlainCouthures** [comment]
XsltForms_domEngine is a global variable which should be defined by the XSLT stylesheet. It has been introduced recently so it might be that the old stylesheet is still in your browser cache.

Thank you for your feedback!

**Comment by nkbl** [comment]
How is the XSL file imported from HTML?

**Comment by AlainCouthures** [comment]
Well, the XSL file is not exactly imported from HTML: there is a processing instruction in the XML source to be interpreted by the browser to call the XSL file which will, then, generated HTML!
