### ISSUE TITLE
Instance viewer broken in rev. 637

### ISSUE THREAD

**Issue by timathom** [AlainCouthures/xsltforms#17]
In rev. 637, the instance viewer in the XSLTForms profiler does not display any instance data.

**Comment by AlainCouthures** [comment]
Sorry, I cannot reproduce this issue yet. Did you try with different browsers? Did you clear the browser cache?

**Comment by timathom** [comment]
Thank you, clearing the browser cache worked, and the instance data now displays. However, XML elements are not indented. (But XML comment nodes and mixed content do seem to preserve space/indentation.)
