### ISSUE TITLE
Request: Provide a 'CDN' for XSLTForms - suggestion : 'github pages'?

### ISSUE THREAD

**Issue by midijohnny** [AlainCouthures/xsltforms#28]
This is request to provide XSLTForms with a CDN link.
One way to consider doing this: enable 'github pages' for this project (or setup a separate dedicated one).

I notice that github serves XML as 'text/plain' (which means XSLTForms won't load in my browser), but 'github pages' serves the same resource as 'xml/application' which works.

Using 'github pages' means you could also put working examples for XForms directly in the project.

Notes:

- There is a slight delay (maybe 1-2mins) before github pages notices any changes.
- I'm not sure if this a good method with regard to versions. (The method I list here always returns the current version in the repo).

```
# GitHub 'raw'
$ export URL=https://raw.githubusercontent.com/midijohnny/xforms-stuff/refs/heads/main/themes.xml
$ curl -s -I -o /dev/null -w '%{content_type}' ${URL}
text/plain; charset=utf-8
```

```
# GitHub Pages:
$ export URL=https://midijohnny.github.io/xforms-stuff/themes.xml
$ curl -s -I -o /dev/null -w '%{content_type}' ${URL}
application/xml
```

**Comment by HeikoTheissen** [comment]
How do you intend to use XSLTForms via CDN?

Even if it was available on github.io (or some other CDN),
```xml
<?xml-stylesheet type="text/xsl" href="https://xyz.github.io/xsltforms/xsltforms.xsl"?>
```
could not be used in XForms documents from different origins. For example, Google Chrome refuses to load it:
> Unsafe attempt to load URL https://xyz.github.io/xsltforms/xsltforms.xsl from frame with URL https://other.domain/xforms.xml. Domains, protocols and ports must match.

**Comment by midijohnny** [comment]
Good point - however - although having it available on the '*.github.io' domain might still be useful.
It would allow other github.io users to reference the xsltforms from their project; allowing them to demonstrate a working Xforms App directly on the site.

Like here: https://midijohnny.github.io/xforms-stuff/show_tables.xml (but I have copied 'xsltforms' into my repo to enable this).

**Comment by HeikoTheissen** [comment]
> It would allow other github.io users to reference the xsltforms from their project; allowing them to demonstrate a working Xforms App directly on the site.

No, that does not work: https://heikotheissen.github.io/markdowntest/vocab.xml gives the error
> Unsafe attempt to load URL https://midijohnny.github.io/xforms-stuff/xsltforms-1.7/xsltforms.xsl from frame with URL https://heikotheissen.github.io/markdowntest/vocab.xml. Domains, protocols and ports must match.

**Comment by midijohnny** [comment]
Ah shame - yes, I see that now. I wrongly assumed CORS only cared about the subdomain.
Oh well - thanks for trying.

**Comment by midijohnny** [comment]
Closing this request - CORS prevents this from working.

**Comment by HeikoTheissen** [comment]
> Closing this request - CORS prevents this from working.

No, https://midijohnny.github.io/xforms-stuff/xsltforms-1.7/xsltforms.xsl _can_ be fetched in CORS mode, because it is served with `Access-Control-Allow-Origin: *`. The problem is that, in Google Chrome at least,
```
<?xml-stylesheet type="text/xsl" href="https://midijohnny.github.io/xforms-stuff/xsltforms-1.7/xsltforms.xsl"?>
```
ignores the CORS header and insists on same-origin.

But in Firefox it works. It would suffice if http://www.agencexml.com/xsltforms/xsltforms/xsltforms.xsl was served with `Access-Control-Allow-Origin: *`.

**Comment by midijohnny** [comment]
No worries, thanks again.

So in summary -  it sounds like the approach of having a 'CDN' for XSLT isn't going to work, so hence closing the issue.
