### ISSUE TITLE
How to use it in PHP?

### ISSUE THREAD

**Issue by rysi3k** [AlainCouthures/xsltforms#3]
Hello @AlainCouthures 
I haven't found nowhere how to use XSLTForms in PHP, how to parse it and display in browser?
Thanks for help.

Greetings

**Comment by AlainCouthures** [comment]
Hello,
There is no specific way to apply XSLTForms stylesheet at server-side with PHP.
Please have a look at this simple example:
`<?php
	$xml = new DOMDocument();
	$xml->load($_GET["form"]);
	$xsl = new DOMDocument();
	$xsl->load("xsltforms/xsltforms.xsl");
	$xslp = new xsltProcessor();
	$xslp->importStyleSheet($xsl);
	$result = $xslp->transformToXml($xml);
	header("Content-Type: text/html");
	echo $result;
?>`
Thank you for you feedback!

**Comment by rysi3k** [comment]
Hi, thanks for help - works like a charm!
